version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  lint:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packages
      - run: npm run lint
  unit:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packages
      - run: npm run test:clean
      - run: npm run test:coverage

workflows:
  tests: 
    jobs:
      - lint
      - unit
